#!/usr/bin/env bash
set -ex

OBJECT_FILE="$1"
SYMBOLS_PATH="$2"
OBJCOPY="$3"

if [ -f "$SYMBOLS_PATH/$OBJECT_FILE" ]; then
  cp $OBJECT_FILE $OBJECT_FILE.old.o

  while read -r line; do
    $OBJCOPY --remove-section="$line" $OBJECT_FILE $OBJECT_FILE
  done < "$SYMBOLS_PATH/$OBJECT_FILE"
fi
